---
title: "Pathological Periodicity, Part I: Relearning the Basics"
author: "Alonso Espinosa Domínguez"
date: "2026-03-15"
categories: [Pathological Periodicity, periodic functions, linear algebra]
---
Let me begin with a more narrative introduction to this series, which will be followed by a more technical one in the next post.

My hiatus from math has been quite long. It's been 9 years since my last algebra class (algebra was one of my weaker subjects, and I regrettably avoided it in favor of taking more analysis classes), a little under 8 years since I seriously attempted any research, 7 years since I gave up on becoming a mathematician, and 6 years since my last math class whatsoever. Needless to say, I am exceedingly rusty. So when life pushed me to reconsider my divorce from mathematics, I thought to myself, *let me revisit the basics.* And hence I picked up Axler's excellent *Linear Algebra Done Right* and began working through the exercises, to start getting the wheels turning again. 

Just in the first chapter, I came across a very innocent-seeming question. Is the set of all periodic functions a vector subspace of $\mathbb{R}^{\mathbb{R}}$, the space of all real-valued functions on $\mathbb{R}$? As rusty as I may be, I was still able to quickly and emphatically answer in the negative. Though sums of functions with commensurable periods are always periodic, *obviously* sums of periodic functions with *incommensurable* periods (i.e., periods whose ratio is irrational) *surely* fail to be periodic. Moreover, the only possible vector subspaces consisting solely of periodic functions would *definitely* have to be made up of functions whose periods are commensurable with one another. I thought to myself, *I will hammer out a quick little proof of this, and I will move on to more exciting things in linear algebra.*

And then I sat down to write and found myself a little bit...stuck. First, I realized I needed to be a bit more precise with what I meant by functions having incommensurable periods. I didn't just need there to *exist* periods $p$ of $f$ and $q$ of $g$ with $p/q \not\in \mathbb{Q}$, I needed *all* periods of $f$ to be incommensurable with those of $g$ in order for $f+g$ to potentially fail to be periodic. This was important to specify because constant functions have the "unusual" property of having incommensurable real numbers in their sets of periods, since their set of periods is just all of $\mathbb{R}$, and this is what makes it possible to add them to any periodic function without affecting the periodicity at all. 

So now I had two questions at once on my mind:

* **Question 1:** Was I wrong about sums of incommensurable functions? That is, can I find a pair of $f, g$ such that they are incommensurable in the sense that they have no periods in common (equivalent to having no periods that are rational multiples of each other) and yet $f+g$ is periodic?
* **Question 2:** Are there any functions other than constant functions that can have two or more incommensurable periods? 

For a brief period (pun intended) of time, I continued believing that the answer to the above would be no. In particular, for the second question, I realized that if a set of periods contains incommensurables, it would have to be dense. And surely, only constant functions could have a dense set of periods, right?

With a little more thought, I concluded this is not hard to prove if I restrict myself to continuous functions...and that the proof for continuous functions cannot really be generalized to all functions. This was precisely the moment I realized I was almost certainly wrong about Question 2, and by extension probably wrong about Question 1 as well. Even the better part of a decade later, I still remember vividly just how pathological a function can get when you abandon continuity. All of a sudden, the prospect of a non-constant function with a dense set of periods seemed like exactly the sort of thing possible in the strange world of nowhere continuous functions. 

So I set out to come up with some examples. Within hours, I had my first example showing Question 2 could be answered affirmatively: if I chose any incommensurable $p, q$, then the characteristic function over $p\mathbb{Q} + q\mathbb{Q}$ would be non-constant and have a set of periods equal to all of $p\mathbb{Q} + q\mathbb{Q}$. 

Question 1 proved to be a bit trickier for me, but after a day or two, I finally came up with an example also answering this question affirmatively. I will discuss this and other examples later; for now I will give any readers a chance to try to come up with examples themselves. Suffice it to say, I was extremely intrigued. And as soon as I answered one question, more questions arose. For instance:

* **Question 3:** Now that I know sums of incommensurable functions do not always fail to be periodic, is there a neat characterization of when these sums end up being periodic?
* **Question 4:** Can I find a vector subspace of $\mathbb{R}^\mathbb{R}$ that consists solely of periodic functions and yet contains two or more incommensurable functions?
* **Question 5:** All the examples I had at that point for both Questions 1 and 2 were constant almost everywhere. Do there exist examples that aren't? Can I find examples that are constant "almost nowhere"? Would these examples have to be non-measurable?
* **Question 6:** Clearly, sets of periods can have some interesting topological and algebraic structure. Sometimes they are dense, and they are always at least an additive group. Sometimes, they are also a vector space over $\mathbb{Q}$. What more can be said about these groups/spaces of periods and how they determine the behavior of the function they arise from?

I can genuinely say, I had not felt this excited about math in at least 8 years. My excitement multiplied even more when I noticed I could invoke the Axiom of Choice to answer Questions 4 and 5 affirmatively as well (except for the measurability part). *[Edit: actually I am pretty sure now that I was wrong about Question 4, though it is not so hard to prove without AC that there are at least $\mathbb{Q}$-vector spaces generated by periodic functions with incommensurable periods. See future posts].* *[Edit2 (04-29-2026): Nevermind! This, and much more, is indeed possible under the assumption that there exists a Vitali set!].* 
 
In other words, here I was, thinking I was just doing a rudimentary exercise in Chapter 1 of a linear algebra text, only to open a can of worms involving many fields of mathematics at once: algebra, measure theory, topology, and set theory. 
 
With a little digging, I learned that unsurprisingly many others have been interested in similar questions. There is, in fact, a substantial body of work on what is called the Periodic Decomposition Problem, which takes many of the questions I had been posing in directions I had not yet imagined ([see for instance this survey paper](https://arxiv.org/abs/1312.3798)). 

I have much more to learn about the work done so far on the Periodic Decomposition Problem. But I do think I have identified some aspects of this problem that haven't been directly tackled in the literature so far. Let me explain: basically the whole line of enquiry in *Pathological Periodicity* is about functions that admit periodic decompositions $h = f+g$ where $f$ and $g$ are incommensurable with each other (and thus with their sum). One of the questions that seems to be unaddressed is about the axiomatics of periodic decompositions, and in particular of *incommensurable* decompositions of functions that are already periodic (a decomposition of an already periodic function into two or more periodic functions will naturally often fail to be an incommensurable decomposition). ZF alone is enough to prove that functions with periodic decompositions exist, but the only *periodic* ones that can be proven to decompose incommensurably in ZF are a.e. constant. Whats more, in ZF alone, it doesn't seem so possible to find conditions on $h$ that are sufficient to guarantee it has a decomposition. On the other hand, in ZFC, there *is* a very simple necesarry *and sufficient* condition on *any* $h$ that determines whether it has a periodic decomposition. As I will show later on in the series, this condition also holds for the "stronger" variant of the problem requiring incommensurability of the summands in the decomposition. Moreover, ZFC abounds with examples of decomposable functions that are not constant a.e., and non-measurable. So, this has led me to wonder which axiom systems "between" ZF and ZFC still allow for the existence of these nonmeasurbale examples, which ones allow for a full solution of the decomposition problem and its "stronger" variant, and whether the classical and the incommensurable variants can be separated from each other by the strength of the axioms needed to prove them (and thus if we can be truly justified in calling the incommensurable variant "stronger" than the original). In other words, I want to figure out the precise "heirarchy" of axioms needed to prove the various versions of the periodic decomposition problem, and to understand how the properties of the functions involved in the decomposition relate to the strength of the axioms needed to prove their existence.

While I work on these questions (and write up the results more formally), I want to use this blog to bring any readers along with me on this journey into the world of *Pathological Periodicity*. I hope you enjoy it as much as I have. See you in the next post!


