---
title: "Exploring Periodicity, Part I: Introduction and Preliminaries"
author: "Alonso Espinosa Domínguez"
date: "2026-03-15"
categories: [Exploring Periodicity, periodic functions, period modules]
---
**1. Introduction**

It is an elementary exercise in linear algebra to show that the set of all periodic functions is not a vector space, since the sum of periodic functions with incommensurable periods (i.e., periods whose ratio is irrational) *may* fail to be periodic. However, this leads to many more subtle questions. For instance:

* Do there exist any periodic functions with incommensurable periods whose sum is nonetheless periodic? Can we characterize such functions? 
* Constant functions are trivially periodic with any real period. Does there exist a non-constant periodic function with 2 or more incommensurable periods? If so, does there exist such a function that is not constant almost everywhere?
* Which subsets of periodic functions are vector spaces? Can any such vector space contain two or more functions with incommensurable periods?
* How do the answers to these questions change when considering various families of periodic functions, such as continuous, strictly periodic, measurable functions, etc.? 

As it turns out, these seemingly simple questions open a can of worms involving many fields of mathematics at once: algebra, measure and ergodic theory, topology of $\mathbb{R}$, and the foundations of mathematics (namely, set theory and the Axiom of Choice). In particular, using the Axiom of Choice on quotients $\mathbb{R}/G$, where $G$ is either a $\mathbb{Z}$-submodule of $\mathbb{R}$ or a $\mathbb{Q}$-subspace of $\mathbb{R}$, we can find highly pathological examples answering the first three questions in the affirmative, but only for non-measurable functions. This is all very closely related to what is called the Periodic Decomposition Problem, about which much has been written ([see for instance this paper](https://arxiv.org/abs/1312.3798)). 

I am working now on figuring out 2 main questions: first, whether the existence of these pathological periodic functions is equivalent to or strictly weaker than the Axiom of Choice (I suspect the latter), and second, just how large the dimension of a vector space of periodic functions can be when it contains functions with incommensurable periods (I suspect not very large). I will write up my findings on these questions more formally in the next few months. However, in the meantime, I want to use this Exploring Periodicity series in the blog to further motivate this line of inquiry and record some elementary proofs I have come up with of classic results related to these questions, but that I won't be including in the final write-up itself, since they are not new. I hope that these elementary proofs will be particularly useful to fellow students of mathematics as well as to instructors, and that they will inspire others to explore these questions further.


**2. Preliminaries**

Let's review some basic definitions and facts about periodic functions that set the stage for our further explorations and that start to reveal the interplay of algebra, topology, and analysis in the world of periodicity.

**Definition 2.1 (Periodic Function)** A function $f:\mathbb{R}\to\mathbb{R}$ is said to be **periodic** if there exists a non-zero real number $p$ such that $f(x+p)=f(x)$ for all $x\in\mathbb{R}$. If there exists a smallest positive such $p$, it is called the **fundamental period** of $f$, and we say $f$ is **strictly periodic**. 

*Remark*: Note that a function can be periodic without being strictly periodic; for instance, the constant functions are periodic with any real period, but they are not strictly periodic. Essentially, the whole line of inquiry that we are following in the first series of this blog is about the existence of non-strictly periodic functions other than the constant functions, in particular those with incommensurable periods.

**Definition 2.2 (The Period Module)** For a periodic function $f:\mathbb{R}\to\mathbb{R}$, we denote by $P_f$ the set of all periods of $f$, i.e., $P_f := \{p\in\mathbb{R}\setminus\{0\} : f(x+p)=f(x) \text{ for all } x\in\mathbb{R}\}$. We call $P_f$ the **period module** of $f$, for reasons that will become clear in a moment. Also, we say $f, g$ are **incommensurable** if $P_f\cap P_g = \{0\}$, and they are **commensurable** otherwise. Note constant functions are trivially commensurable with any periodic function, since they are periodic with any period.

**Definition 2.3 ($\mathbb{Z}$-submodule and its dimension)** A subset $M$ of $\mathbb{R}$ is called a **$\mathbb{Z}$-submodule** if it is closed under addition and under multiplication by integers. The **dimension** of a $\mathbb{Z}$-submodule $M$ is the cardinality of a maximal linearly independent subset of $M$ over $\mathbb{Z}$.

**Definition 2.4 ($\mathbb{Q}$-subspace and Period Space)** For any periodic function $f$, we can consider the linear span of its period module over the rational numbers $\mathbb{Q}$. We denote this by $V_f := \text{span}_\mathbb{Q}(P_f)$, and call it the **period space** of $f$. By definition, $V_f$ is a **$\mathbb{Q}$-subspace** of $\mathbb{R}$. 

We immediately find some basic facts about periodic functions:

* *Fact 0*: If $f, g$ are incommensurable, their periods are irrational multiples of each other. This is because if $p\in P_f$ and $q\in P_g$ are such that $p/q\in\mathbb{Q}$, then there exist integers $n, m$ such that $np = mq$, and thus $np\in P_f\cap P_g$, showing that $f$ and $g$ are not incommensurable.
* *Fact 1*: If $p, q$ are periods of a function $f$, then $p+q$ is also a period of $f$. Generally, if $f$ is periodic with period $p$, then it is also periodic with respect to any integer linear combinations of periods of $f$. This means **$P_f$ is a $\mathbb{Z}$-submodule of $\mathbb{R}$.**
* *Fact 2*: If $f$ is strictly periodic with fundamental period $p$, then the set of all periods of $f$ is precisely the $\mathbb{Z}$-module $p\mathbb{Z}:= \{np : n\in\mathbb{Z}\}$. I.e., $P_f$ is necessarily *a one-dimensional submodule*.
* *Fact 3*: The dimension of the period module $P_f$ as a $\mathbb{Z}$-module is not necessarily the same as the dimension of the period space $V_f$ as a $\mathbb{Q}$-vector space. For instance, if $P_f = \mathbb{Q}$, its dimension as a $\mathbb{Z}$-module is infinite, but its dimension as a $\mathbb{Q}$-subspace ($V_f = \mathbb{Q}$) is exactly 1. 
* *Fact 4*: If $f$ is *continuous* and periodic, then it is either constant or strictly periodic. This can be shown as follows: For a given $x,y\in\mathbb{R}$ with $f(y)\neq f(x)$, continuity means that $y^\prime=\inf\{z>x\mid f(z)=f(y)\}>x$. Thus $y^\prime-x$ must be a positive number less than any positive period of $f$. Hence the infimum $p$ of positive periods must be greater than zero. If $p$ itself were not a period, we could find two distinct periods arbitrarily close to $p$, and their difference would be a period smaller than $p$, violating the infimum. Thus $p$ is the fundamentgal period of $f$, and $f$ is strictly periodic.

Now recall the definition of a dense set:

**Definition 2.5 (Dense Set)** A subset $S$ of $\mathbb{R}$ is said to be *dense* if for every open interval $(a,b)$, there exists an element of $S$ in that interval. Equivalently, the closure of $S$ is $\mathbb{R}$.

We are now ready to see our first result about periodic functions with incommensurable periods, which relates the topology of period sets to their algebraic structure:

**Proposition 2.6**: *If $p, q$ are incommensurable ($p/q\not\in \mathbb{Q}$), then the $\mathbb{Z}$-module $\mathbb{Z}_{p,q}:=\{np + mq : n,m\in\mathbb{Z}\}$ is dense in $\mathbb{R}$. In particular, if a function $f$ has two incommensurable periods $p$ and $q$, then it is periodic with respect to every element of $\mathbb{Z}_{p,q}$, and thus has a dense set of periods and is not strictly periodic. Therefore **the only such functions that are continuous are constant functions.***

*Proof*: To see the first part of the proposition, we make use of the fact that irrationals can be approximated by rationals very nicely: by Dirichlet's approximation theorem, we know that for any $\epsilon>0$, we can find integers $-n, m$ such that $|mp/q -(-n)|<\epsilon/q$, and thus $|mp +nq|<\epsilon$. This shows all intervals containing the origin have elements of $\mathbb{Z}_{p,q}$. Now take any interval $(a, b)$. By the foregoing, we can find $x,y\in\mathbb{Z}_{p,q}$ with $|x|\leq|a|$, and 
$$0<|y|<\min\left(\{|x-b|, |x-a|, |b-a|\}\setminus{\{0\}}\right)$$
Where we remove $0$ in case $x=a$. There thus must be some integer $n$ so that $x+ny\in (a, b)$. But by Fact 1, $x+ny$ is also a period of $f$. Thus $\mathbb{Z}_{p,q}$ is dense in $\mathbb{R}$. The second part of the proposition follows immediately from the first part and from the previous facts.

The reader can now verify the following corollary, which is a direct consequence of the previous proposition and facts:

**Corollary 2.7:** *Let $f, g$ be continuous. Then $f+g$ is periodic if and only if they are commensurable.*

*Remark*: This corollary is actually false if we drop continuity, even for strictly periodic functions $f,g$, as we will see in the next section.

**3. Functions with higher-dimensional period modules and spaces**

Most of the time, when we think of periodic functions, we think of nice, well-behaved functions like sines and cosines. From the perspective of their period modules, these are all rather boring: they are all one-dimensional over $\mathbb{Z}$, none of them are dense, and any vector spaces $\mathcal V$ consisting solely of strictly periodic functions cannot contain any incommensurable functions, meaning the period spaces $V_f$ for all $f\in \mathcal V$ live along a single 1-dimensional line $p\mathbb{Q}$ of $\mathbb{R}$. 

It is natural to ask if there are any non-constant functions with dense and/or higher-dimensional period modules and spaces, and relatedly if there are incommensurable functions whose sum is periodic.

The answer to both questions is yes!

*Example 3.1*: Let $p, q$ be incommensurable, and consider the functions $\mathbb{1}_{\mathbb{Q}}$, $\mathbb{1}_{\mathbb{Z}_{p,q}}$, and 
$$
   \begin{split}
    &f(x) = 
    \begin{cases}
         0 & \text{if } x \not\in \mathbb{Z}_{p,q}\\
        n & \text{if } x = mp+nq\in \mathbb{Z}_{p,q}
    \end{cases} \\ &\text{ and } \\
    &g(x) = 
    \begin{cases}
        0 & \text{if } x \not\in \mathbb{Z}_{p,q}\\
        -m & \text{if } x = mp+nq\in \mathbb{Z}_{p,q}
    \end{cases}
\end{split}
$$

Notice $\mathbb{1}_{\mathbb{Q}}$ has a period module equal to $\mathbb{Q}$, which is dense and has infinite dimension as a $\mathbb{Z}$-module, but its period space $V_f$ has dimension 1 over $\mathbb{Q}$. 

Meanwhile, $\mathbb{1}_{\mathbb{Z}_{p,q}}$ has a period module equal to $\mathbb{Z}_{p,q}$, which is also dense and has dimension 2 as a $\mathbb{Z}$-module (and its period space $V_f$ also has dimension 2 over $\mathbb{Q}$). 

As for $f$ and $g$, note $P_f = p\mathbb{Z}$ and $P_g = q\mathbb{Z}$. They are strictly periodic and incommensurable. However, evaluating $(f+g)(x)$ for $x = mp+nq$ yields $n-m$. If we translate by $p+q$, we get $(m+1)p + (n+1)q$, which maps to $(n+1)-(m+1) = n-m$. Thus, $P_{f+g} = (p+q)\mathbb{Z}$. They are incommensurable, strictly periodic functions whose sum is strictly periodic! 

These examples, however, are all constant almost everywhere. But, as alluded to earlier, we *can* find pathological examples using the Axiom of Choice that are constant almost nowhere. When attempting to venture into this world, we come up against the formidable wall of measurability: all such examples we can find are non-measurable.

In the next installment of *Exploring Periodicity*, we will first find a periodic function with a dense period module that is constant only on sets of measure zero, and then we will show that if we require our functions to be measurable, then the only functions with dense period modules are constant almost everywhere. Stay tuned!