---
title: "Pathological Periodicity, Part III: The First Pathological examples"
author: "Alonso Espinosa Domínguez"
date: "2026-03-19"
categories: [measure theory, periodic functions]
draft: true
number-offset: 2
crossref:
  chapters: true
---


# The First Pathologies 

::: {#exm-dense-periods}
## Periodic functions with dense period modules
Let $M$ be any $\mathbb{Z}$-submodule of $\mathbb{R}$. The characteristic function $\mathbf{1}_M$ is periodic with $P_{\mathbf{1}_M} = M$. Thus, the problem of proving existence of a periodic function with a period module satisfying some collection of conditions is equivalent to the problem of finding a submodule of $\mathbb{R}$ satisfying the conditions. In particular, any higher-rank $M$ gives rise to a periodic function with incommensurable periods. Such higher-rank submodules $M$ include, for instance
$$
M= \bigoplus_{i\in\mathcal I} p_i\mathbb{Z}
$${#eq-gexample}
whenever $\{p_i\}_{i\in\mathcal I}$ is a collection (possibly infinite) of 2 or more $\mathbb{Q}$-linearly independent real numbers. The rank of $M$ in this case is equal to the cardinality of $\mathcal I$. If we repalce $\mathbb{Z}$ with $\mathbb{Q}$, the module becomes a $\mathbb{Q}$-vector space, and the rank becomes the dimension.
:::

In a future post, we will further explore submodules and subspaces of $\mathbb R$ and in particular those of infinite rank/dimension in greater depth. For now, we proceed to an example of incommensurable strictly periodic functions whose sum is periodic.

::: {#exm-incommensurable-sum}
## Incommensurable, strictly periodic functions with a strictly periodic sum
Let $p, q$ be incommensurable, and define
$$
   \begin{split}
    &f(x) = 
    \begin{cases}
        n & \text{if } x = mp+nq\in \mathbb{Z}_{p,q}\\
         0 & \text{if } x \not\in \mathbb{Z}_{p,q}
    \end{cases} \\ &\text{ and } \\
    &g(x) = 
    \begin{cases}
        -m & \text{if } x = mp+nq\in \mathbb{Z}_{p,q}\\
        0 & \text{if } x \not\in \mathbb{Z}_{p,q}
    \end{cases}
\end{split}
$$

Notice $P_f = p\mathbb{Z}$ and $P_g = q\mathbb{Z}$. They are strictly periodic and incommensurable. However, evaluating $(f+g)(x)$ for $x = mp+nq$ yields $n-m$. If we translate by $p+q$, we get $(m+1)p + (n+1)q$, which maps to $(n+1)-(m+1) = n-m$. Since $\mathbb{R}\setminus \mathbb{Z}_{p,q}$ is also invariant under translation by $p+q$, we have that $P_{f+g} = (p+q)\mathbb{Z}$. They are incommensurable, strictly periodic functions whose sum is strictly periodic!
:::
Let $h= f+g$ as in the previous example. We collect some observations about $f, g, h$:

:::{#prp-incommensurable-sum}

:::
Notice however that these examples are constant almost everywhere, and that $\alpha f + \beta g$ is periodic if and only if $\alpha/\beta\in \mathbb{Q}$. This immediately leads to at least three more questions:

::: {.open-question}
**Open questions.**

1. Must all periodic functions with the above behaviour be constant a.e.?
2. What is the maximum dimension a period space can have?
3. Is there any pair of incommensurable functions whose linear span over $\mathbb{R}$ consists solely of periodic functions (i.e. $\alpha f + \beta g$ is periodic for all $\alpha, \beta \in \mathbb{R}$)?
:::

# Using the Axiom of Choice

Let's dive right in:

::: {#prp-ac-existence}
There exists a periodic function $f$ with incommensurable periods such that $f$ is constant only on sets of measure zero.
:::

::: {.proof}
Let $G$ be a $\mathbb{Z}$-submodule of $\mathbb{R}$ with rank at least 2 and measure zero (i.e., something like @eq-gexample for a countable $\mathcal I$ with 2 or more elements), and let $X$ be a set of representatives of the quotient $\mathbb{R}/G$ (which exists by the axiom of choice). Define $f:\mathbb{R}\to\mathbb{R}$ by $f(x) = r$ if $x\in r+G$ for some $r\in X$. This function is periodic with period module containing $G$, and thus has a dense period module. Moreover, it is constant only on sets of the form $r+G$, which all have measure zero.
:::

::: {.remark}
We can also now find pairs of strictly periodic functions $f, g$ with incommensurable periods such that $f+g$ is periodic, and all three functions are constant only on sets of measure zero. Namely, in the functions $f, g$ defined in @exm-incommensurable-sum we can replace 0 with the pathological function as in @prp-ac-existence but with $G = \mathbb{Z}_{p,q}$. This makes it so that $f$ and $g$ are strictly periodic with incommensurable periods, their sum is strictly periodic, and all three functions are constant only on sets of measure zero.
:::

In the next installment of *Pathological Periodicity* we will then prove that none of the functions we have found with AC are measurable, because measurable functions with dense period sets must be constant a.e. Next, we will explore period modules and spaces in more detail, and tackle the question about the maximal dimension of period spaces. Finally, the fourth installment will more explicitly tie all we have done to the Periodic Decomposition Problem, and will tackle the third of the above questions. Stay tuned!